include ../Makefile.defs

EXTRAFLAGS := -O3 -I/usr/local/cuda/include -L /usr/local/cuda/lib64/ -lcudart -DUSE_PINNED=1

################################################################################
#
# Include any special rule for this testcase here! Usually:
#
# static:
#
# dynamic:
#
################################################################################

include ../Makefile.rules
